title: Snakemake Executor Plugin Documentation Example
description: An example site using the snakemake-plugin-docs Jekyll theme
baseurl: /snakemake-plugin-docs-example

# These is provided with the template, but you can override here
nav_logo_file: assets/img/snakemake-logo.png
footer_logo_file: assets/img/snakemake-logo.png

# Info /message at the top
info_bar: true # Bar at the top of all pages. Delete this line or set to false for no info bar display.
info_bar_text: This site is part of the <a href="" target="_blank" class="text-white text-underline">Snakemake Plugins</a> collection.
footer_text: Snakemake plugins are a community effort for the <a href="https://github.com/snakemake" class="text-white text-underline">Snakemake project</a> <br>&copy; Copyright 2023, under the terms of the <a href="https://github.com/snakemake/snakemake/blob/main/LICENSE.md" class="text-white text-underline">MIT License</a>.
permalink: pretty

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: true

github_link: true
github_pages_branch: main

# Social
github_username: snakemake
# linkedin_username: company/lawrence-livermore-national-laboratory
# twitter_username: vsoch

# Theme for docs
plugins:
  - jekyll-remote-theme

remote_theme: snakemake/snakemake-plugin-docs-jekyll


exclude:
 - _assets
 - Gemfile
 - Gemfile.lock
 - vendor
 - .github